datapath: './data/dichalcogenides_public'
test_datapath: './data/dichalcogenides_private'
checkpoint_path: './callback/val_mae_00023_0.005869_fold1.hdf5'

model:
  epochs: 800
  batch_size: 128
  lr: 2e-4 
  cutoff: 4


